services:
  app:
    image: louislam/uptime-kuma:2.1.3
    restart: always
    volumes:
      - data:/app/data
    networks:
      - frontend
      - backend
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=3001

  tailscale:
    image: tailscale/tailscale:v1.94
    hostname: kuma
    restart: always
    environment:
      - TS_SOCKS5_SERVER=0.0.0.0:1055 
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--reset --accept-dns=false --accept-routes
    volumes:
      - tsdata:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    networks:
      - backend

volumes:
  data:
  tsdata:

networks:
  frontend:
    name: proxy_frontend
    external: true
  backend:
